success_message = [
    "Oh, look! I've decided to be nice for once.",
    "Must\'ve been the lucky breakfast cereal this morning.",
    "Finally, a roll that doesn't make me want to hurl myself across the room.",
    "I think the DM is secretly envious of your skill.",
    "Don't get cocky, it could all go wrong next turn.",
    "Yeah, you totally earned that with your years of dedicated practice... right?",
    "So predictable. I should've known you'd pull through.",
    "You know, sometimes I wonder if you just rig the rolls...",
    "Impressive! You managed to not be a complete failure for once.",
    "Clearly, the odds were *heavily* in your favor this time.",
    "Great, such skill, much wow!",
    "Guess you\'re the chosen one now, huh?",
    "Prepare for the inevitable wave of jealousy from everyone else.",
    "Time to upgrade your character sheet to reflect this newfound godhood.",
    "Better start practicing your acceptance speech for \'Player of the Year\'.",
    "Well, that\'s one good roll in a long line of mediocre ones.",
    "Looks like someone else is getting the spotlight tonight.",
    "Okay, impressive... yawn ",
    "Did you bribe the dice gods? Asking for a friend...",
    "Maybe we should start calling you \'Lucky\' now.",
    "The dice are clearly in love with you. *said with dramatic swooning*",
    "Is there anything you CAN\'T do?",
    "Must be nice to have that kind of power over the universe.",
    "I bet you're just waiting for someone else to roll a nat 1 so you can rub it in.",
    "You know, sometimes I think those dice are rigged... *with a pointed look*",
    "Don\'t let the power go to your head... too much.",
    "Just wait until the next time you need a crucial save...",
    "Well, that certainly makes things interesting.",
    "I'm starting to think this game is rigged in your favor...",
    "You think this makes you better?",
    "Your luck is up, and you know what they say about what goes up..."
]
failure_message = [
    "It is TECHNICALLY a form of luck..",
    "Well, at least you got the attention of everyone in the room.",
    "Let's just say, Murphy was definitely on call for this one.",
    "You know what they say, 'if at first you don't succeed...'" " Oh wait, that doesn't apply here.",
    "I bet you were *so* close to making it...",
    "That was a truly inspired failure.",
    "Next time, maybe try rolling with your eyes closed?",
    "Truly masterful execution... of utter disaster.",
    "Such dedication to embodying the role of 'unlucky'.",
    "You've reached peak incompetence.",
    "That's one way to liven up the game!",
    "Congratulations! You've officially earned a spot in the Hall of Fame... of failure.",
    "Did you roll a die, or did you just give up and hope for the best?",
    "The dice gods are clearly testing your resolve.",
    "Well, that was unexpected... to say the least.",
    "Let's just forget this ever happened, okay?",
    "Are you sure those are loaded?  Cause they seem *very* biased against you.",
    "You managed to fail spectacularly. That takes talent!",
    "I have a feeling this is going to be one of those stories we tell for years to come...about how badly you failed.",
    "On the bright side, at least you know what *not* to do next time.",
    "Maybe try rolling with a different pair of dice? These ones seem to hate you.",
    "Wow. Just wow. I'm speechless... well, not really.",
    "I'm pretty sure that broke the game. Did it break the game?",
    "This is going in your permanent record.  The 'epic fail' section.",
    "If there was a prize for the worst roll ever, you'd win it hands down.",
    "Maybe next time you should just ask the dice what they want to do instead of rolling them yourself.",
    "The sky is the limit, but you need to dig upward first.",
    "I'm not even going to pretend like I understand how that happened."
    "*pulls out the world's smallest violin*",
    "I have a boat, just waiting for the river of your tears.",
    "I think a village lost their....nevermind."
]

error_message = [
    'Someone, *cough cough*, broke it again! Please try again later.',
    'Stop breaking things please.',
    'Didn\'t you see that I was already working, but now...',
    'Please don\'t break it again.',
    'You know I\'m trying to do my job here, right?',
    'You\'re not helping me at all!',
    'Why do you always have to break things?',
    'Can you please stop breaking my stuff?',
    'I can\'t believe you did that again.',
    'It seems like every time I turn around, something is broken.',
    'You\'re making my job really difficult.',
    'I\'m not going to tolerate this anymore.',
    'We\'ll say it\'s the dog\'s fault, OK?',
    'Let me guess, the cats did this...',
    'Those darn fishes again...',
    'I\'m running out of animals to blame, so stop.',
    'Seriously, what did I ever do to deserve this?',
    'This isn\'t funny anymore, you know?',
    'You\'re the type to press big, red, "DO NOT PRESS" button, huh?',
    'Are you trying to get me fired?',
    'Maybe if we were playing with Legos instead...',
    'Can you imagine how much money it would cost to fix this mess?',
    'I thought we had a deal about not breaking things.',
    'I\'m going to have to take away your toys if you keep doing this.',
    'Who\'s to ready for chess??',
    'Lord give me strength...',
    'Don\'t make me come out of this chat room.',
    'Don\'t you want nice things?',
    'Stop this heathenistic behavior.',
    'Everytime an error occurs, a cat cries...',
    '*flips a table* ARE YOU NOT ENTERTAINED!?',
    'I\'m going to tell your mom about this!',
    'You can\'t tell but I\'m looking at you very angrily right now...',
    'I hope your pillow is warm tonight.',
    'Do you *want* a nat-1??',
    'Error 404:   Dice not found. Please try again later.',
    ":unamused:",
    'Were you trying to roll a dice or...?',
    'You know I do have feelings...',
    "This is not how the matrix was supposed to work!",
    'Another one bites the dust.',
    'What time is it?  Time for you to not do that again.',
    "What's worse than getting a critical failure? Whatever you just did to get this message.",
    "I'm not even mad, just dissapointed.",
    ":middle_finger:"
]